image: Visual Studio 2019

install:
  - cinst Boxstarter -r --no-progress
build_script:
- ps: |-4
    Write-Host "Building..."
    $repoPath = Join-Path $env:APPVEYOR_BUILD_FOLDER "boxstarter\"
    Set-BoxstarterConfig -LocalRepo "$repoPath"
    Invoke-BoxstarterBuild Leemw1977Installer
artifacts:
- path: '*.nupkg'
  name: Nuget Packages